### ISSUE TITLE
Include LICENSE into PyPi's release archive

### ISSUE THREAD

**Issue by yegorich** [rcmachado/tomako#1]
Could you add LICENSE file to PyPI's archive? It is needed in Buildroot, when gathering legal info and Python package is fetched from PyPI and not from GitHub.

Thanks

**Comment by rcmachado** [comment]
`LICENSE` file added and generated version 0.1.0.post1 (no changes from 0.1.0 besides the `LICENSE` file). See https://pypi.python.org/pypi/tomako.
